from __future__ import annotations

TRAIN_WINDOW_YEARS = 20
FORECAST_HORIZON = 5
MIN_SERIES_LENGTH = 30
ANOMALY_WINDOW = 10
ANOMALY_Z_THRESHOLD = 2.5

ROLLING_STATISTICS_WINDOW = 10

DEFAULT_FORECASTER_TIMEOUT_SECONDS = 300.0
DEFAULT_LEMONADE_TIMEOUT_SECONDS = 300.0

